/* =====================================================
   VORTEX TIER — PLAYER DATA
   This file is generated by the Admin Panel.
   Replace this file on your website to update players.
====================================================== */

const VORTEX_PLAYERS = [
];
