/* =====================================================
   VORTEX TIER â€” GENERATED APP.JS
   Generated from Admin Panel
====================================================== */

const VORTEX_DATA = {
  "players": [
    {
      "name": "Se9ku",
      "region": "AS",
      "skin": "",
      "namemc": "",
      "results": {
        "vanilla": {
          "tier": "LT5",
          "points": 5
        },
        "uhc": {
          "tier": "",
          "points": 0
        },
        "pot": {
          "tier": "",
          "points": 0
        },
        "nethop": {
          "tier": "",
          "points": 0
        },
        "smp": {
          "tier": "",
          "points": 0
        },
        "sword": {
          "tier": "",
          "points": 0
        },
        "axe": {
          "tier": "",
          "points": 0
        },
        "mace": {
          "tier": "",
          "points": 0
        }
      }
    }
  ]
};

/*
  The player database above was generated by
  Vortex Tier Admin Panel.

  IMPORTANT:
  Keep your existing Vortex frontend rendering
  functions below this data section.
*/
